version: '3.8'

services:
  keepalived-anchor:
    image: rjchicago/keepalived-anchor:${VERSION:-latest}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - KEEPALIVED_IMAGE=rjchicago/keepalived-float:${VERSION:-latest}
      - KEEPALIVED_INTERFACE=bond0
      - KEEPALIVED_VIRTUAL_IPS
      - DOCKER_NODE_HOSTNAME={{.Node.Hostname}}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
  keepalived-buoy:
    image: rjchicago/keepalived-buoy:${VERSION:-latest}
    ports:
      - target: 3000
        published: 8082
        protocol: tcp
        mode: host
    environment:
      DOCKER_NODE_HOSTNAME: "{{.Node.Hostname}}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
