#!/usr/bin/env bash

CONTAINER_NAME=keepalived_worker

echo "Removing $CONTAINER_NAME"
docker rm $CONTAINER_NAME -f

echo "Pulling image from repo"
docker pull $IMAGE

echo "Starting $CONTAINER_NAME"
docker run -d --init --name=$CONTAINER_NAME --rm \
  --cap-add=NET_ADMIN --net=host --pid=host \
  --label hidden \
  -e KEEPALIVED_INTERFACE=$KEEPALIVED_INTERFACE \
  -e KEEPALIVED_VIRTUAL_IPS=$KEEPALIVED_VIRTUAL_IPS \
  -e KEEPALIVED_ROUTER_ID=${KEEPALIVED_ROUTER_ID:-77} \
  -e KEEPALIVED_CHECK_SCRIPT="${KEEPALIVED_CHECK_SCRIPT:-/usr/bin/pgrep -f keepalived_tether}" \
  -e KEEPALIVED_CHECK_INTERVAL=${KEEPALIVED_CHECK_INTERVAL:-1} \
  -e KEEPALIVED_PRIORITY=${KEEPALIVED_PRIORITY:-100} \
  $IMAGE

npm run start