#!/usr/bin/env bash

echo "KEEPALIVED_INTERFACE: $KEEPALIVED_INTERFACE"
echo "KEEPALIVED_ROUTER_ID: $KEEPALIVED_ROUTER_ID"
echo "KEEPALIVED_PRIORITY: $KEEPALIVED_PRIORITY"
echo "KEEPALIVED_VIRTUAL_IPS: $KEEPALIVED_VIRTUAL_IPS"
echo "KEEPALIVED_CHECK_SCRIPT: $KEEPALIVED_CHECK_SCRIPT"
echo "KEEPALIVED_CHECK_INTERVAL: $KEEPALIVED_CHECK_INTERVAL"

echo ""

echo "
global_defs {
        enable_script_security
}
vrrp_script chk_script {
        script "$KEEPALIVED_CHECK_SCRIPT"
        interval $KEEPALIVED_CHECK_INTERVAL
}
vrrp_instance VI_1 {
        interface $KEEPALIVED_INTERFACE
        state BACKUP
        nopreempt
        virtual_router_id $KEEPALIVED_ROUTER_ID

        priority $KEEPALIVED_PRIORITY
        virtual_ipaddress {
           $KEEPALIVED_VIRTUAL_IPS
        }
        track_script {
           chk_script
        }
}" > /etc/keepalived/keepalived.conf

keepalived --dont-fork --log-console